module.exports = {
  Produtos: require('./Produtos'),
  Clientes: require('./Clientes'),
  Fornecedores: require('./Fornecedores'),
  Ordens: require('./Ordens'),
  Compras: require('./Compras'),
  Inventario: require('./Inventario'),
  Vendas: require('./Vendas'),
  Relatorios: require('./Relatorios'),
  Configuracoes: require('./Configuracoes'),
  Cadastro: require('./Cadastro'),
  RedefinirSenha: require('./RedefinirSenha'),
  Login: require('./Login'),
  Dashboard: require('./Dashboard'),
} 